"""Keep Python support metadata and CI environments in sync.

The scheduled Python support workflow calls this script after detecting a new
CPython release or a NumPy minimum-version change.  It deliberately edits only
the version lists owned by this repository; the Pixi lockfile is regenerated by
the workflow after this script completes.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PIXI = ROOT / "pixi.toml"
PYPROJECT = ROOT / "pyproject.toml"
README = ROOT / "README.md"
WRAPPER = ROOT / "scripts/mojagg.ps1"
MATRIX_FILES = (ROOT / ".github/workflows/ci.yml", ROOT / ".github/workflows/release.yml")
PYTHON_CYCLE_RE = re.compile(r"^(?P<major>\d+)\.(?P<minor>\d+)$")


def normalize_cycle(value: str) -> str:
    """Return a ``major.minor`` Python cycle or raise a useful error."""

    match = PYTHON_CYCLE_RE.fullmatch(value.strip().removeprefix("py"))
    if match is None:
        raise ValueError(f"invalid Python cycle: {value!r}")
    return f"{match.group('major')}.{match.group('minor')}"


def cycle_key(cycle: str) -> tuple[int, int]:
    major, minor = normalize_cycle(cycle).split(".")
    return int(major), int(minor)


def environment_name(cycle: str) -> str:
    return "py" + normalize_cycle(cycle).replace(".", "")


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")


def feature_cycles(pixi: str) -> set[str]:
    return {
        f"{match.group(1)}.{match.group(2)}"
        for match in re.finditer(r"^\[feature\.py(\d)(\d+)\.dependencies\]$", pixi, re.MULTILINE)
    }


def update_pixi(pixi: str, additions: set[str], removals: set[str], target: set[str]) -> str:
    """Update Pixi features, environments, and the minimum Python constraint."""

    for cycle in sorted(removals, key=cycle_key):
        compact = environment_name(cycle)
        pattern = re.compile(
            rf"^\[feature\.{re.escape(compact)}\.dependencies\]\r?\n"
            rf"python = \"{re.escape(cycle)}\.\*\"\r?\n\r?\n?",
            re.MULTILINE,
        )
        pixi, count = pattern.subn("", pixi, count=1)
        if count != 1:
            raise ValueError(f"could not remove Pixi feature for Python {cycle}")

    for cycle in sorted(additions, key=cycle_key, reverse=True):
        compact = environment_name(cycle)
        if f"[feature.{compact}.dependencies]" in pixi:
            continue
        block = f'[feature.{compact}.dependencies]\npython = "{cycle}.*"\n\n'
        pixi, count = re.subn(
            r"^\[environments\]$", block + "[environments]", pixi, count=1, flags=re.MULTILINE
        )
        if count != 1:
            raise ValueError("could not find the Pixi environments section")

    for cycle in sorted(removals, key=cycle_key):
        compact = environment_name(cycle)
        pixi, count = re.subn(
            rf"^{re.escape(compact)} = \[\"{re.escape(compact)}\"\]\r?\n?",
            "",
            pixi,
            count=1,
            flags=re.MULTILINE,
        )
        if count != 1:
            raise ValueError(f"could not remove Pixi environment for Python {cycle}")

    environment_lines = "".join(
        f'{environment_name(cycle)} = ["{environment_name(cycle)}"]\n'
        for cycle in sorted(target, key=cycle_key)
    )
    environment_pattern = re.compile(r"(?ms)(^\[environments\]\r?\n).*\Z")
    match = environment_pattern.search(pixi)
    if match is None:
        raise ValueError("could not find the Pixi environments section")
    pixi = pixi[: match.start(1)] + "[environments]\n" + environment_lines

    minimum = min(target, key=cycle_key)
    pixi, count = re.subn(
        r'(?m)^python = ">=\d+\.\d+"$',
        f'python = ">={minimum}"',
        pixi,
        count=1,
    )
    if count != 1:
        raise ValueError("could not update Pixi's minimum Python constraint")
    return pixi


def update_matrix(content: str, target: set[str], path: Path) -> str:
    pattern = re.compile(r"(?m)^(\s*environment:\s*\[)[^\]\r\n]+(\])$")
    matches = list(pattern.finditer(content))
    if len(matches) != 1:
        raise ValueError(f"expected one environment matrix in {path}, found {len(matches)}")
    environments = ", ".join(
        f'"{environment_name(cycle)}"' for cycle in sorted(target, key=cycle_key)
    )
    replacement = rf"\g<1>{environments}\g<2>"
    content, count = pattern.subn(replacement, content, count=1)
    if count != 1:
        raise ValueError(f"could not find the environment matrix in {path}")
    return content


def update_pyproject(
    content: str, additions: set[str], removals: set[str], target: set[str]
) -> str:
    for cycle in sorted(removals, key=cycle_key):
        line = f'    "Programming Language :: Python :: {cycle}",\n'
        if line not in content:
            raise ValueError(f"could not remove Python {cycle} from pyproject.toml")
        content = content.replace(line, "", 1)

    classifier_matches = list(
        re.finditer(r'^    "Programming Language :: Python :: (\d+\.\d+)",$', content, re.MULTILINE)
    )
    if not classifier_matches:
        raise ValueError("could not find Python classifiers in pyproject.toml")
    for cycle in sorted(additions, key=cycle_key):
        line = f'    "Programming Language :: Python :: {cycle}",'
        if line in content:
            continue
        classifier_matches = list(
            re.finditer(
                r'^    "Programming Language :: Python :: (\d+\.\d+)",$', content, re.MULTILINE
            )
        )
        insert_at = classifier_matches[-1].end()
        content = (
            content[:insert_at]
            + f'\n    "Programming Language :: Python :: {cycle}",'
            + content[insert_at:]
        )

    minimum = min(target, key=cycle_key)
    content, count = re.subn(
        r'^requires-python = ">=\d+\.\d+"$',
        f'requires-python = ">={minimum}"',
        content,
        count=1,
        flags=re.MULTILINE,
    )
    if count != 1:
        raise ValueError("could not update requires-python in pyproject.toml")
    return content


def update_readme(content: str, target: set[str]) -> str:
    minimum = min(target, key=cycle_key)
    return re.sub(
        r"Python\s*(?:\u2265|>=)\s*\d+\.\d+",
        f"Python \u2265 {minimum}",
        content,
        count=1,
    )


def update_wrapper(content: str, target: set[str]) -> str:
    environments = [f"--env {environment_name(cycle)}" for cycle in sorted(target, key=cycle_key)]
    replacement = (
        "choose another locked environment with "
        + ", ".join(environments[:-1])
        + ",\n"
        + "or "
        + environments[-1]
        + "."
    )
    content, count = re.subn(
        r"choose another locked environment with --env [^\r\n]+\r?\n"
        r"or --env [^\r\n]+\.",
        replacement,
        content,
        count=1,
    )
    if count != 1:
        raise ValueError("could not update the wrapper's environment help")
    return content


def apply_actions(actions: list[dict[str, str]]) -> tuple[set[str], set[str], set[str]]:
    pixi = read(PIXI)
    current = feature_cycles(pixi)
    additions = {
        normalize_cycle(action["version"]) for action in actions if action["type"] == "add"
    }
    removals = {
        normalize_cycle(action["version"]) for action in actions if action["type"] == "remove"
    }
    unknown_types = {action["type"] for action in actions} - {"add", "remove"}
    if unknown_types:
        raise ValueError(f"unknown action types: {sorted(unknown_types)}")
    if additions & removals:
        raise ValueError("the same Python cycle cannot be added and removed in one update")
    if not removals <= current:
        raise ValueError(f"cannot remove unsupported Python cycles: {sorted(removals - current)}")
    target = (current | additions) - removals
    if not target:
        raise ValueError("the update would remove every supported Python version")

    updated_pixi = update_pixi(pixi, additions, removals, target)
    pyproject = read(PYPROJECT)
    updated_pyproject = update_pyproject(pyproject, additions, removals, target)
    updated_readme = update_readme(read(README), target)
    updated_wrapper = update_wrapper(read(WRAPPER), target)
    updated_matrices = {path: update_matrix(read(path), target, path) for path in MATRIX_FILES}

    write(PIXI, updated_pixi)
    write(PYPROJECT, updated_pyproject)
    write(README, updated_readme)
    write(WRAPPER, updated_wrapper)
    for path, content in updated_matrices.items():
        write(path, content)
    return current, additions, removals


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--actions",
        required=True,
        help='JSON list such as [{"type":"add","version":"3.15"}]',
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    actions = json.loads(args.actions)
    if not isinstance(actions, list) or not all(isinstance(action, dict) for action in actions):
        raise SystemExit("--actions must be a JSON list of objects")
    current, additions, removals = apply_actions(actions)
    print(
        "Updated Python support: "
        f"{', '.join(sorted(current, key=cycle_key))} -> "
        f"{', '.join(sorted((current | additions) - removals, key=cycle_key))}"
    )


if __name__ == "__main__":
    main()
